### ISSUE TITLE
Could not load file or assembly system.threading.tasks.extensions

### ISSUE THREAD

**Issue by z1137** [KrachDev/SaveTracker#8]
When I launched the game, the following error occurred:

[error starting game tracking: Could not load file or assembly "system.threading.tasks.extensions, version=4.2.0.1, culture=neutral, publickeytoken=cc7b13ffcd2ddd51" or one of its dependencies. system could not find the file specified.]

When I close the game, a prompt appears:

[error during game stop: Object reference not set to an instance of an object.]

**Comment by KrachDev** [comment]
This issue might be caused by a conflict with another plugin. I can help diagnose it if you provide the following:

Your Playnite version

Your log files

You can find the logs here:

If using the installed version:
%AppData%\Playnite\log\playnite.log
%AppData%\Playnite\log\extensions.log

If using the portable version:
<PlayniteFolder>/Playnite/log/playnite.log
<PlayniteFolder>/Playnite/log/extensions.log

**Comment by z1137** [comment]
playnite version: 10.45

[playnite.log](https://github.com/user-attachments/files/23973259/playnite.log)
[extensions.log](https://github.com/user-attachments/files/23973260/extensions.log)

**Comment by KrachDev** [comment]
Reading the log files didn’t show me any abnormalities. Also, I tried to replicate your setup on my side but I wasn’t met with the same error. If you could provide me with the Debug log from the console, there might be something in there.

To enable the Debug Console:

1. Open Playnite
2. Click on the Side Panel button (it has a cloud icon and the SaveTracker tooltip)
3. Check “Show Debug Console”
4. Click the Save button
Now try to replicate whatever produces the issue. Once it does, copy all of the content from the console and paste it here.

Sorry for the inconvenience. Although this plugin may not be maintained long-term, I will still help with any catastrophic errors. I also suggest trying the desktop version:
https://github.com/KrachDev/SaveTrackerDesktop

**Comment by z1137** [comment]
```
[17:17:06.347 | DATA] ============================================================
[17:17:06.347 | DATA]   SAVETRACKER DEBUG CONSOLE
[17:17:06.347 | DATA]   Started: 2025-12-06 17:17:06
[17:17:06.347 | DATA] ============================================================
[17:17:06.347 | DATA]
[17:17:06.347 | DATA] [INFO] SaveTracker plugin initialized
[17:17:06.347 | DATA] [INFO] Cloud Provider: GoogleDrive
[17:17:07.265 | DATA] [INFO] GetSidebarItems called
[17:17:07.380 | DATA] Generating TopPanelItems for current view...
[17:17:12.123 | DATA]
[17:17:12.123 | DATA] ============================================================
[17:17:12.124 | DATA]   GAME STARTED
[17:17:12.124 | DATA] ============================================================
[17:17:12.124 | DATA] Game Name: Kinky Dungeon
[17:17:12.124 | DATA] Start Time: 2025/12/6 17:17:12
[17:17:12.124 | DATA] Game Source: itch.io
[17:17:12.124 | DATA] Plugin ID: 00000000-0000-0000-0000-000000000000
[17:17:12.124 | DATA] Is Standalone: False
[17:17:12.124 | DATA] [INFO] Game launched via launcher: itch.io

libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
[17:17:17.200 | DATA] [INFO] Game detected at: KinkyDungeon.exe
[17:17:17.200 | DATA] Game Path: KinkyDungeon.exe
[17:17:17.210 | DATA] [EXCEPTION] OnGameStarted: Could not load file or assembly"System.Threading.Tasks.Extensions, Version=4.2.0.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51"or one of its dependencies. system could not find the file specified.
[17:17:17.222 | DATA] [STACK TRACE]    System.Text.Json.JsonSerializer.Serialize[TValue](TValue value, JsonSerializerOptions options)
   SaveTracker.SaveTracker.<OnGameStarted>d__19.MoveNext()
[17:17:29.456 | DATA] [EXCEPTION] OnGameStopped: Object reference not set to an instance of an object
[17:17:29.456 | DATA] [STACK TRACE]    SaveTracker.SaveTracker.<OnGameStopped>d__20.MoveNext()

```

**Comment by z1137** [comment]
I tried the desktop version, and it worked when run with Playnite.
but, I found that only games added to the App could be tracked.
This means I need to repeatedly add the Playnite game library to the App, and Playnite currently has 3000 games in its library...

Also, some games may have different save file names, which means that after the initial upload, only the .savetracker_checksums.json file will be uploaded.

<img width="1027" height="571" alt="Image" src="https://github.com/user-attachments/assets/5d52057f-ea18-4c9c-8633-26aed0e3c9e1" />

<img width="372" height="203" alt="Image" src="https://github.com/user-attachments/assets/eeff3112-90fd-4352-ab64-9284099e6d2a" />

**Comment by KrachDev** [comment]
I believe I have fixed the issue you encountered in the next release, along with the addition of a Playnite import button to help with the problem. And thanks for your feedback — it gives good insights for the different games out there and how their save systems work.

The update will be released in a few hours and you should be prompted to update.

P.S.: Currently the Playnite addition system relies on another extension, `JsonLibraryImportExport`, which you can find [here](https://github.com/sokolinthesky/JsonLibraryImportExport)
You will need it to export your library, since I couldn’t crack Playnite’s `.db` structure for now.

Thanks again.

**Comment by z1137** [comment]
The App added Playnite's library and ran successfully.
However, for games not located on the C drive, it only tracked some unnecessary caches.
Save files in the game's root directory and subfolders were not tracked, even after updates. Is there a good solution to this?

**Comment by KrachDev** [comment]
Interesting! If it's the same game, this is expected behavior, it's an `Electron ` game that uses a different approach to saves. It works like a browser, which is why it might look like it's saving useless data, but it's actually capturing the saves. That's what much of my testing covers.
If it's not the same game, or you've seen this in multiple other games, could you please provide their names? My latest release actually addressed this issue and made the blacklist system drive-agnostic.

**Comment by z1137** [comment]
The game used for testing was made with the RPG Maker MV engine.
I used version 0.4.5! masterpiece! The app tracked the game created with RPG Maker MV game.

<img width="1268" height="983" alt="Image" src="https://github.com/user-attachments/assets/ae0a3520-bffc-4375-9659-24a4d0ab86e3" />

 thank you for the fix!

**Comment by z1137** [comment]
As for the other game I mentioned that isn't on the C drive and can't be tracked, it's called 【勇者に寛容すぎるファンタジー世界RPG】, which was made using the RPG Maker MZ engine. The App still can't work on it.

**Comment by KrachDev** [comment]
Nice to hear it worked for you! If you can share the logs from one of your sessions via the debug console for the game, I might be able to figure out the cause. The current system I set up always expects saves to be on the C: drive, or more generally, on the system drive. Even if the game is installed on another drive, most likely the save would still be in the game path, which I reference as %GAMEPATH%.

**Comment by z1137** [comment]
[console log.txt](https://github.com/user-attachments/files/24064393/console.log.txt)

![Image](https://github.com/user-attachments/assets/2dc0e0b5-7024-4bb5-bbdb-232853926fc3)

**Comment by KrachDev** [comment]
I see that you’re still using the Playnite version. Even though the desktop version was originally based on it, the Playnite build is now way out of date. The systems have gone through a complete overhaul on the desktop side, and they’re almost not compatible with each other anymore.

I recommend sticking with the desktop version I’m sure it will work perfectly for your use case.

P.S.: I’ll be adding support soon for saves that were uploaded by the Playnite plugin so they’ll work properly in the desktop version.

**Comment by z1137** [comment]
Thank you so lot. I succeeded on the desktop version. Previously, I opened the App through Playnite's library—software tool—App took over all the functionality. It appears that this process caused the Playnite plugin to override the App.
I've reversed the order of this process, and it works perfectly. Thank you for maintaining the software and plugins. Look forward to more good news regarding future software features.

PS: The reason I opened the App through Playnite is because it skips the App's library loading process, and Playnite has many convenient features...

**Comment by KrachDev** [comment]
Thank you for the feedback, I really appreciate it. It helps a lot in shaping the direction of the app. I’ll keep improving the integration with launchers like Playnite and Steam and others to make everything more seamless. The goal is to move toward a true fire-and-forget experience where the app handles save detection and management automatically in the background.

P.S. I’ve already figured out the structure of Playnite’s .db format, so that integration is coming sooner rather than later.
